from tes_helpers import run_simple_test
import deck

def test_get_starting_pace():
    tests = {
        (2, "No Variant"): 17,
        (3, "Rainbow (5 Suits)"): 13,
        (4, "Dual-Color (5 Suits)"): 13,
        (5, "Extremely Ambiguous (5 Suits)"): 10,
        (6, "White Reversed (5 Suits)"): 13,
        (2, "6 Suits"): 22,
        (3, "Ambiguous & Dual-Color"): 18,
        (4, "RGB Mix (6 Suits)"): 18,
        (5, "Alternating Clues (6 Suits)"): 15,
        (6, "Holiday Mix (6 Suits)"): 18,
        (2, "Black (6 Suits)"): 17,
        (3, "Candy Corn Mix (6 Suits)"): 13,
        (4, "Special Mix (6 Suits)"): 13,
        (5, "Null-Ones & Dark Null (6 Suits)"): 10,
        (6, "Valentine Mix (6 Suits)"): 13,
        (2, "Gray (5 Suits)"): 12,
        (3, "Holiday Mix (5 Suits)"): 8,
        (4, "Special Mix (5 Suits)"): 8,
        (5, "Dark Rainbow Reversed (5 Suits)"): 5,
        (6, "Ambiguous & Dark Brown (5 Suits)"): 8,
        (2, "Pink (4 Suits)"): 12,
        (3, "Dual-Color & White (4 Suits)"): 8,
        (4, "Matryoshka (4 Suits)"): 8,
        (5, "Synesthesia (4 Suits)"): 5,
        (6, "Duck (4 Suits)"): 8,
        (2, "3 Suits"): 7,
        (3, "Funnels (3 Suits)"): 3,
        (4, "Chimneys (3 Suits)"): 3,
        (5, "Color Mute (3 Suits)"): 0,
        (6, "Number Mute (3 Suits)"): 3,
        (2, "Critical Fours (5 Suits)"): 12,
        (3, "Critical Fours (5 Suits)"): 8,
        (4, "Critical Fours (5 Suits)"): 8,
        (5, "Critical Fours (5 Suits)"): 5,
        (6, "Critical Fours (5 Suits)"): 8,
        (2, "Critical Fours (6 Suits)"): 16,
        (3, "Critical Fours (6 Suits)"): 12,
        (4, "Critical Fours (6 Suits)"): 12,
        (5, "Critical Fours (6 Suits)"): 9,
        (6, "Critical Fours (6 Suits)"): 12,
        (2, "Black & Dark Rainbow (6 Suits)"): 12,
        (3, "Gray & Gray Pink (6 Suits)"): 8,
        (4, "Dark Omni & Dark Null (6 Suits)"): 8,
        (5, "Dark Pink & Cocoa Rainbow (6 Suits)"): 5,
        (6, "Dark Brown & Dark Prism (6 Suits)"): 8,
        (2, "Clue Starved (5 Suits)"): 17,
        (3, "Clue Starved & Rainbow (5 Suits)"): 13,
        (4, "Clue Starved & Brown (5 Suits)"): 13,
        (5, "Clue Starved & White (5 Suits)"): 10,
        (6, "Clue Starved & Null (5 Suits)"): 13,
        (2, "Clue Starved (6 Suits)"): 22,
        (3, "Clue Starved & Rainbow (6 Suits)"): 18,
        (4, "Clue Starved & Brown (6 Suits)"): 18,
        (5, "Clue Starved & White (6 Suits)"): 15,
        (6, "Clue Starved & Null (6 Suits)"): 18,
    }
    run_simple_test(deck.get_starting_pace, tests)


def test_get_starting_efficiency():
    tests = {
        (2, "No Variant"): 25 / 29,
        (3, "Rainbow (5 Suits)"): 1.0,
        (4, "Dual-Color (5 Suits)"): 1.0,
        (5, "Extremely Ambiguous (5 Suits)"): 25 / 21,
        (6, "White Reversed (5 Suits)"): 25 / 24,
        (2, "6 Suits"): 30 / 35,
        (3, "Ambiguous & Dual-Color"): 30 / 31,
        (4, "RGB Mix (6 Suits)"): 30 / 31,
        (5, "Alternating Clues (6 Suits)"): 10 / 9,
        (6, "Holiday Mix (6 Suits)"): 1.0,
        (2, "Black (6 Suits)"): 1.0,
        (3, "Candy Corn Mix (6 Suits)"): 15 / 13,
        (4, "Special Mix (6 Suits)"): 15 / 13,
        (5, "Null-Ones & Dark Null (6 Suits)"): 15 / 11,
        (6, "Valentine Mix (6 Suits)"): 1.2,
        (2, "Gray (5 Suits)"): 25 / 24,
        (3, "Holiday Mix (5 Suits)"): 1.25,
        (4, "Special Mix (5 Suits)"): 1.25,
        (5, "Dark Rainbow Reversed (5 Suits)"): 1.5625,
        (6, "Ambiguous & Dark Brown (5 Suits)"): 25 / 19,
        (2, "Pink (4 Suits)"): 20 / 23,
        (3, "Dual-Color & White (4 Suits)"): 20 / 19,
        (4, "Matryoshka (4 Suits)"): 20 / 19,
        (5, "Synesthesia (4 Suits)"): 4 / 3,
        (6, "Duck (4 Suits)"): 10 / 9,
        (2, "3 Suits"): 15 / 17,
        (3, "Funnels (3 Suits)"): 15 / 13,
        (4, "Chimneys (3 Suits)"): 15 / 13,
        (5, "Color Mute (3 Suits)"): 5 / 3,
        (6, "Number Mute (3 Suits)"): 1.25,
        (2, "Critical Fours (5 Suits)"): 25 / 24,
        (3, "Critical Fours (5 Suits)"): 1.25,
        (4, "Critical Fours (5 Suits)"): 1.25,
        (5, "Critical Fours (5 Suits)"): 1.5625,
        (6, "Critical Fours (5 Suits)"): 25 / 19,
        (2, "Critical Fours (6 Suits)"): 30 / 29,
        (3, "Critical Fours (6 Suits)"): 1.2,
        (4, "Critical Fours (6 Suits)"): 1.2,
        (5, "Critical Fours (6 Suits)"): 10 / 7,
        (6, "Critical Fours (6 Suits)"): 1.25,
        (2, "Black & Dark Rainbow (6 Suits)"): 1.2,
        (3, "Gray & Gray Pink (6 Suits)"): 10 / 7,
        (4, "Dark Omni & Dark Null (6 Suits)"): 10 / 7,
        (5, "Dark Pink & Cocoa Rainbow (6 Suits)"): 30 / 17,
        (6, "Dark Brown & Dark Prism (6 Suits)"): 1.5,
        (2, "Clue Starved (5 Suits)"): 25 / 18,
        (3, "Clue Starved & Rainbow (5 Suits)"): 1.5625,
        (4, "Clue Starved & Brown (5 Suits)"): 1.5625,
        (5, "Clue Starved & White (5 Suits)"): 25 / 14,
        (6, "Clue Starved & Null (5 Suits)"): 1.5625,
        (2, "Clue Starved (6 Suits)"): 10 / 7,
        (3, "Clue Starved & Rainbow (6 Suits)"): 30 / 19,
        (4, "Clue Starved & Brown (6 Suits)"): 30 / 19,
        (5, "Clue Starved & White (6 Suits)"): 30 / 17,
        (6, "Clue Starved & Null (6 Suits)"): 30 / 19,
    }
    run_simple_test(deck.get_starting_efficiency, tests)

if __name__ == '__main__':
    test_get_starting_pace()
    test_get_starting_efficiency()